-- phase-1 exploratory analysis
-- 1 total revenue generated by the food delivery app

SELECT SUM(order_amount-discount) AS total_revenue
FROM orders;

-- 2 TOTAL ORDERS PER CITY
SELECT r.city, COUNT(o.order_id) AS total_orders
FROM orders o
JOIN restaurants r ON o.restaurant_id = r.restaurant_id
GROUP BY r.city
ORDER BY total_orders DESC;

-- 3 TOP 10 CUSTOMERS BY SPENDING
SELECT c.name, SUM(o.order_amount - o.discount) AS total_spent
FROM orders o
JOIN customers c ON o.customer_id = c.customer_id
GROUP BY c.customer_id
ORDER BY total_spent DESC
LIMIT 10;

-- PHASE 2 CUSTOMER SEGMENTATION
-- 4 CUSTOMER CATEGORY (GOLDEN, SILVER, BRONZE) BASED ON SPENDING
SELECT 
       c.name,
       SUM(o.order_amount - o.discount) AS total_spent,
       CASE 
           WHEN SUM(o.order_amount - o.discount) >= 7000 THEN 'GOLDEN'
           WHEN SUM(o.order_amount - o.discount) >= 2000 THEN 'SILVER'
           ELSE 'BRONZE'
       END AS customer_category
FROM orders o
JOIN customers c ON o.customer_id = c.customer_id
GROUP BY c.customer_id, c.name
ORDER BY total_spent DESC;

--  PHASE 3 — RESTAURANT PERFORMANCE
-- 5.Top 10 Restaurants by Revenue

SELECT 
    r.restaurant_id,
    r.restaurant_name,
    r.city,
    SUM(o.order_amount - o.discount) AS total_revenue
FROM orders o
JOIN restaurants r 
ON o.restaurant_id = r.restaurant_id
GROUP BY r.restaurant_id, r.restaurant_name, r.city
ORDER BY total_revenue DESC
LIMIT 10;

-- 6. Average Rating vs Revenue

SELECT 
    r.restaurant_name,
    AVG(r.rating) AS avg_rating,
    SUM(o.order_amount - o.discount) AS total_revenue
FROM orders o
JOIN restaurants r ON o.restaurant_id = r.restaurant_id
GROUP BY r.restaurant_id, r.restaurant_name
ORDER BY total_revenue DESC;

 -- PHASE 4 — DELIVERY ANALYSIS
-- 7. Average Delivery Time Per City
SELECT 
    r.city,
    AVG(o.delivery_time) AS avg_delivery_time
FROM orders o
JOIN restaurants r ON o.restaurant_id = r.restaurant_id
GROUP BY r.city
ORDER BY avg_delivery_time DESC;

-- 8. Late Deliveries (Above 45 Minutes)
SELECT 
    r.city,
    COUNT(*) AS late_deliveries
FROM orders o
JOIN restaurants r ON o.restaurant_id = r.restaurant_id
WHERE o.delivery_time > 45
GROUP BY r.city
ORDER BY late_deliveries DESC;

-- PHASE 5 — PAYMENT & DISCOUNT ANALYSIS
-- 9.Payment Method Distribution

SELECT 
    payment_method,
    COUNT(*) AS total_orders
FROM orders
GROUP BY payment_method
ORDER BY total_orders DESC;

-- 10. Discount Impact on Revenue
SELECT 
    SUM(discount) AS total_discount,
    SUM(order_amount - discount) AS net_revenue
FROM orders;
-- PHASE 6 — ADVANCED SQL
-- 11.Monthly Revenue Using CTE

WITH monthly_revenue AS (
    SELECT 
        MONTH(order_date) AS month,
        SUM(order_amount - discount) AS revenue
    FROM orders
    GROUP BY MONTH(order_date)
)
SELECT month, revenue FROM monthly_revenue
order by month;

-- 12.Rank Restaurants by Revenue (Window Function)

SELECT 
    r.restaurant_name,
    SUM(o.order_amount - o.discount) AS total_revenue,
    DENSE_RANK() OVER (ORDER BY SUM(o.order_amount - o.discount) DESC) AS revenue_rank
FROM orders o
JOIN restaurants r ON o.restaurant_id = r.restaurant_id
GROUP BY r.restaurant_id, r.restaurant_name
ORDER BY total_revenue DESC;

-- 13.Above Average Revenue Restaurants (Subquery)
SELECT 
    r.restaurant_name,
    SUM(o.order_amount - o.discount) AS total_revenue
FROM orders o
JOIN restaurants r ON o.restaurant_id = r.restaurant_id
GROUP BY r.restaurant_id, r.restaurant_name
HAVING SUM(o.order_amount - o.discount) > (
    SELECT AVG(total_revenue)
    FROM (
        SELECT SUM(o2.order_amount - o2.discount) AS total_revenue
        FROM orders o2
        GROUP BY o2.restaurant_id
    ) avg_revenue
);

-- PHASE 7 — DATABASE OBJECTS
-- 14.Create Revenue View
CREATE VIEW revenue_view AS
SELECT 
    r.restaurant_id,
    r.restaurant_name,
    r.city,
    SUM(o.order_amount - o.discount) AS total_revenue
FROM orders o
JOIN restaurants r ON o.restaurant_id = r.restaurant_id
GROUP BY r.restaurant_id, r.restaurant_name, r.city;

-- 15.Stored Procedure to Get Top N Restaurant

CREATE PROCEDURE get_top_n_restaurants(IN TOP_n INT)
BEGIN
    set @limit_value = TOP_n;

    set @sql_query = CONCAT(
        'SELECT 
            restaurant_id,
            restaurant_name,
            city,
            total_revenue
        FROM revenue_view
        ORDER BY total_revenue DESC
        LIMIT ', @limit_value
    );
    PREPARE stmt FROM @sql_query;
    EXECUTE stmt;   
    DEALLOCATE PREPARE stmt;
END;

call get_top_n_restaurants(10);


